server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: stateless 
zuul:
  routes:
    meusistema-struts:
      url: http://localhost:8081
    agilepromoter2:
      url: http://localhost:8080
